POST https://plugin.inulogic.binboum.eu/update
Content-Type: application/json

{
    "repo": "my-repo",
    "branch": "my-branch",
    "serviceData": {
        "repo": "my-repo",
        "branch": "my-branch",
        "tag": "my-tag"
    }
}

###
POST https://plugin.inulogic.binboum.eu/update
Content-Type: application/json

{
    "repo": "my-repo",
    "branch": "my-other-branch",
    "serviceData": {
        "repo": "my-repo",
        "branch": "my-other-branch",
        "tag": "my-other-tag"
    }
}

###
POST https://plugin.inulogic.binboum.eu/update
Content-Type: application/json

{
    "repo": "your-repo",
    "branch": "your-branch",
    "serviceData": {
        "repo": "your-repo",
        "branch": "your-branch",
        "tag": "your-tag"
    }
}

###
POST https://plugin.inulogic.binboum.eu/update
Content-Type: application/json

{
    "repo": "{{ .repo }}",
    "branch": "{{ .branch }}",
    "serviceData": {
        "repo": "my-repo",
        "branch": "my-branch",
        "tag": "my-tag"
    }
}


###
POST https://plugin.inulogic.binboum.eu/api/v1/template.execute
Content-Type: application/json

{
    "repo": "my-repo"
}

###
POST https://plugin.inulogic.binboum.eu/api/v1/template.execute
Content-Type: application/json

{
    "repo": "your-repo",
    "branch": "your-branch"
}

###
POST https://plugin.inulogic.binboum.eu/api/v1/template.execute
Content-Type: application/json

{
    "repo": "argo-test"
}
